### ISSUE TITLE
scrolling back to top loses headers

### ISSUE THREAD

**Issue by chaals** [w3c/Unitas#42] opened 2016-04-07 18:44 UTC
Yandex Browser 16.3 on Mac OS

If I open e.g. a group page, scroll down, then scroll back to the top, I can no longer read the header. (I'm not sure if this is related to #37 or not), but it's a bug…

**Comment by tripu** [comment] 2016-04-08 02:46
You mean the whole blue overlay disappears, or just the title (the name of the group, on white letters)?

**Comment by chaals** [comment] 2016-04-08 08:39
Just the title - there is something of a trace of it, but not enough to read

**Comment by tripu** [comment] 2016-04-11 03:51
@chaals, I tried to reproduce the error with Yandex Browser for Linux, but it looks OK for me.

&hellip;OK, barring a known issue with the width of the white title on the blue overlay, that is. #38: we are truncating long titles to keep the layout &ldquo;right&rdquo; and make sure it doesn't wrap over multiple lines.

Is that the problem you are referring to? (If not, a screenshot of the page and of the developer tools with HTML classes and CSS properties may be useful to debug.)

**Comment by tripu** [comment] 2016-04-28 14:43
Closing it, as I understand it's a duplicate of #38.
Please reopen and elaborate (screenshot?) if not.

**Closed by tripu** 2016-04-28 14:43 UTC
Labels: bug, duplicate
